# <?php die(); ?>
core:
  FilterChain:
    name: FilterChain
    files:
      - classes/FilterChain.php
      - classes/base/BaseFilter.php
  URLHander:
    name: URLHandler
    files:
      - classes/URLHandler.php

  ACLFilter:
    name: ACLFilter
    files:
      - filters/ACLFilter.php
  ValidationFilter:
    name: ValidationFilter
    files:
      - filters/ValidationFilter.php
  URLHandlerFilter:
    name: URLHandlerFilter
    files:
      - filters/URLHandlerFilter.php
  ActionLoaderFilter:
    name: ACLFilter
    files:
      - filters/ActionLoaderFilter.php
  RenderFilter:
    name: ACLFilter
    files:
      - filters/RenderFilter.php
    
